# Port Server
server:
  port: 8000

# Spring App Properties
spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri:
            lb://USER-SERVICE
          predicates:
            - Path=/auth/**, /api/users/**
        - id: MESSAGE-SERVICE
          uri:
            lb://MESSAGE-SERVICE
          predicates:
            - Path=/api/messages/**
        - id: IMAGE-SERVICE
          uri:
            lb://IMAGE-SERVICE
          predicates:
            - Path=/api/images/**
        - id: PRODUCT-SERVICE
          uri:
            lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**
        - id: ORDER-SERVICE
          uri:
            lb://ORDER-SERVICE
          predicates:
            - Path=/api/orders/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

# Eureka Properties
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka
