# Port Server
server:
  port: 8002

# Spring App
spring:
  application:
    name: MESSAGE-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/socialmedia
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

# Eureka Properties
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
